///|
pub impl[A : Clone, B : Clone] Clone for (A, B) with clone(self) {
  let (a, b) = self
  (a.clone(), b.clone())
}

///|
pub impl[A : Clone, B : Clone, C : Clone] Clone for (A, B, C) with clone(self) {
  let (a, b, c) = self
  (a.clone(), b.clone(), c.clone())
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone] Clone for (A, B, C, D) with clone(
  self
) {
  let (a, b, c, d) = self
  (a.clone(), b.clone(), c.clone(), d.clone())
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
) with clone(self) {
  let (a, b, c, d, e) = self
  (a.clone(), b.clone(), c.clone(), d.clone(), e.clone())
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
) with clone(self) {
  let (a, b, c, d, e, f) = self
  (a.clone(), b.clone(), c.clone(), d.clone(), e.clone(), f.clone())
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone, G : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
  G,
) with clone(self) {
  let (a, b, c, d, e, f, g) = self
  (a.clone(), b.clone(), c.clone(), d.clone(), e.clone(), f.clone(), g.clone())
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone, G : Clone, H : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
) with clone(self) {
  let (a, b, c, d, e, f, g, h) = self
  (
    a.clone(),
    b.clone(),
    c.clone(),
    d.clone(),
    e.clone(),
    f.clone(),
    g.clone(),
    h.clone(),
  )
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone, G : Clone, H : Clone, I : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
) with clone(self) {
  let (a, b, c, d, e, f, g, h, i) = self
  (
    a.clone(),
    b.clone(),
    c.clone(),
    d.clone(),
    e.clone(),
    f.clone(),
    g.clone(),
    h.clone(),
    i.clone(),
  )
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone, G : Clone, H : Clone, I : Clone, J : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
) with clone(self) {
  let (a, b, c, d, e, f, g, h, i, j) = self
  (
    a.clone(),
    b.clone(),
    c.clone(),
    d.clone(),
    e.clone(),
    f.clone(),
    g.clone(),
    h.clone(),
    i.clone(),
    j.clone(),
  )
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone, G : Clone, H : Clone, I : Clone, J : Clone, K : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
) with clone(self) {
  let (a, b, c, d, e, f, g, h, i, j, k) = self
  (
    a.clone(),
    b.clone(),
    c.clone(),
    d.clone(),
    e.clone(),
    f.clone(),
    g.clone(),
    h.clone(),
    i.clone(),
    j.clone(),
    k.clone(),
  )
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone, G : Clone, H : Clone, I : Clone, J : Clone, K : Clone, L : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
) with clone(self) {
  let (a, b, c, d, e, f, g, h, i, j, k, l) = self
  (
    a.clone(),
    b.clone(),
    c.clone(),
    d.clone(),
    e.clone(),
    f.clone(),
    g.clone(),
    h.clone(),
    i.clone(),
    j.clone(),
    k.clone(),
    l.clone(),
  )
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone, G : Clone, H : Clone, I : Clone, J : Clone, K : Clone, L : Clone, M : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
) with clone(self) {
  let (a, b, c, d, e, f, g, h, i, j, k, l, m) = self
  (
    a.clone(),
    b.clone(),
    c.clone(),
    d.clone(),
    e.clone(),
    f.clone(),
    g.clone(),
    h.clone(),
    i.clone(),
    j.clone(),
    k.clone(),
    l.clone(),
    m.clone(),
  )
}

///|
pub impl[A : Clone, B : Clone, C : Clone, D : Clone, E : Clone, F : Clone, G : Clone, H : Clone, I : Clone, J : Clone, K : Clone, L : Clone, M : Clone, N : Clone] Clone for (
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
) with clone(self) {
  let (a, b, c, d, e, f, g, h, i, j, k, l, m, n) = self
  (
    a.clone(),
    b.clone(),
    c.clone(),
    d.clone(),
    e.clone(),
    f.clone(),
    g.clone(),
    h.clone(),
    i.clone(),
    j.clone(),
    k.clone(),
    l.clone(),
    m.clone(),
    n.clone(),
  )
}
